config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles do
    resources :comments
  end

  resources :slogans

  resources :pages
 

  root to: 'pages#show', id: 'home'

  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  put '/signin', to: 'sessions#new'

  get ':id', to: 'pages#show', as: :view  
end

app/models/slogan.rb
# == Schema Information
#
# Table name: slogans
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Slogan < ActiveRecord::Base
end

app/controllers/slogans_controller.rb
class SlogansController < ApplicationController
  before_action :set_slogan, only: [:show, :edit, :update, :destroy]

  # GET /slogans
  # GET /slogans.json
  def index
    @slogans = Slogan.all
  end

  # GET /slogans/1
  # GET /slogans/1.json
  def show
  end

  # GET /slogans/new
  def new
    @slogan = Slogan.new
  end

  # GET /slogans/1/edit
  def edit
  end

  # POST /slogans
  # POST /slogans.json
  def create
    @slogan = Slogan.new(slogan_params)

    respond_to do |format|
      if @slogan.save
        format.html { redirect_to @slogan, notice: 'Slogan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @slogan }
      else
        format.html { render action: 'new' }
        format.json { render json: @slogan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slogans/1
  # PATCH/PUT /slogans/1.json
  def update
    respond_to do |format|
      if @slogan.update(slogan_params)
        format.html { redirect_to @slogan, notice: 'Slogan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @slogan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slogans/1
  # DELETE /slogans/1.json
  def destroy
    @slogan.destroy
    respond_to do |format|
      format.html { redirect_to slogans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slogan
      @slogan = Slogan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slogan_params
      params.require(:slogan).permit(:name)
    end
end

app/views/slogans/_form.html.erb
<%= simple_form_for @slogan do |f| %>
  <% f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/slogans/edit.html.erb
<h1>Editing slogan</h1>

<%= render 'form' %>

<%= link_to 'Show', @slogan %> |
<%= link_to 'Back', slogans_path %>

app/views/slogans/index.html.erb
<h1>Listing slogans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @slogans.each do |slogan| %>
    <tr>
      <td><%= slogan.name %></td>
      <td><%= link_to 'Show', slogan %></td>
      <td><%= link_to 'Edit', edit_slogan_path(slogan) %></td>
      <td><%= link_to 'Destroy', slogan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Slogan', new_slogan_path %>

app/views/slogans/new.html.erb
<h1>New slogan</h1>

<%= render 'form' %>

<%= link_to 'Back', slogans_path %>

app/views/slogans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slogan.name %>
</p>


<%= link_to 'Edit', edit_slogan_path(@slogan) %> |
<%= link_to 'Back', slogans_path %>