config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles do
    resources :comments
  end

  resources :slogans

  resources :pages
 

  root to: 'pages#show', id: 'home'

  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  put '/signin', to: 'sessions#new'

  get ':id', to: 'pages#show', as: :view  
end

app/views/layouts/_brand.html.erb
<header class="navbar">
    <div class="container-fluid">
        <div class="navbar-header col-md-offset-1">
          <%= link_to image_tag("TransHamco.png", alt: "Hamco Internet Solutions"), root_path, class: 'brand' %>
        </div>

        <div class="col-md-7 col-md-offset-1">
          <div class='saying'><%= Slogan.count == 0 ? 'Testing?' : Slogan.order("RANDOM()").first.name %></div>
        </div>
  </div>

</header>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
        <small>
          <a href="http://www.hamcois.com/">Hamco Internet Solutions</a>
        </small>
        <nav>
          <ul>
            <li><%= link_to "About",   "/about" %></li>
            <li><%= link_to "Contact", "/contact" %></li>
            <% if signed_in? %>
              <li><%= link_to 'Sign Out', signout_path, method: "delete" %>
            <% else %>
              <li><%= link_to 'Sign In', signin_path %></li>
            <% end %>
          </ul>
        </nav>
  </div>
 

</footer>



app/views/layouts/_googleanalytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19500335-2']);
  _gaq.push(['_setDomainName', 'hamcois.com']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb

  
        <div class="col-sm-1 col-sm-offset-1">
          <ul class="nav nav-pills nav-stacked">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: (current_page?(root_path) ? 'nav-link active' : 'nav-link') %>
            </li>
            <li class="nav-item">
              <%= link_to 'Articles', articles_path, class: (current_page?(articles_path) ? 'nav-link active' : 'nav-link') %>
            </li>
          </ul>
        </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="col-md-3">
<img class="paperclip" <%= image_tag("paperclip.png", alt: "paperclip") %> </>
<div class="sidebar">
  <h3>Stuff I think</h3>
  <% recent_articles %> 
  <% @recent_articles.each do |article| %>
  <h4><%= article.title %></h4>
  <h5><%= article.created_at.to_date.strftime("%m-%d-%Y") %></h5>
  <p><%= article.content.split[0..15].join(" ") %>...<br>
  <%= link_to "See More", article %>
  </p>
  <% end %> 
</div>




<img class="paperclip" <%= image_tag("paperclip.png", alt: "paperclip") %> </>
<div class="sidebar">
  <h3>Stuff I like.</h3>
  <h4>Links to peek at.</h4>
  <h5>Some of these are worth reading.</h5>
  <p>We picked Ruby on Rails because of the amazing community.  Here are some places you could look if you're interested in starting.<br>
  <a href=http://rubyonrails.org>Rails</a><br>
  <a href=http://Railscasts.com>Railscasts</a><br>
  <a href=http://ruby.railstutorial.org>Rails Tutorial</a><br>
  <a href=http://github.com>Github</a><br>
  <a href=http://Railsinstaller.com>Rails Installer</a><br>
  <a href=http://vagrantup.com>Vagrant</a><br>
  </p>  
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title><%= full_title(yield(:title)) %></title>
   <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Hamco Internet Solutions" %>">
   <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
   <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
   <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
   <%= yield(:head) %>
   <meta name="keywords" content="website keywords, website keywords" />
   <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
   <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz" />
   <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Tangerine" />

  </head>
  <body>
    <%= render 'layouts/brand' %>
      <div class="container-fluid">
          <%= render 'layouts/navigation' %>
          <div class="col-md-5">
            <div id="site_content">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
            <%= render 'layouts/sidebar' %>
      </div>
      <%= render 'layouts/footer' %>
      <%= debug(assigns) if Rails.env.development? %>
      <%= render 'layouts/googleanalytics' if Rails.env.production? %>
   </body>
</html>